# Generated by Django 4.2.4 on 2024-05-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('viewer', 'viewer'), ('editor', 'editor'), ('owner', 'owner')], max_length=20),
        ),
    ]
