# Generated by Django 4.2.4 on 2024-05-09 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('Editor', 'Editor'), ('Viewer', 'Viewer'), ('Owner', 'Owner')], max_length=20)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank_app.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
