# Generated by Django 4.2.4 on 2024-05-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank_app', '0002_usertopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
