# Generated by Django 4.2.4 on 2024-05-10 09:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank_app', '0003_topic_deleted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='topic',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
    ]
