# Generated by Django 4.2.11 on 2024-07-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank_app', '0005_testpaper_test_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpaper',
            name='total_time_to_solve',
        ),
        migrations.AddField(
            model_name='testpaper',
            name='qid',
            field=models.ManyToManyField(to='question_bank_app.questionbank'),
        ),
        migrations.AddField(
            model_name='testpaper',
            name='time_to_solve',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testpaper',
            name='test_name',
            field=models.CharField(default='xyz', max_length=10, unique=True),
        ),
        migrations.DeleteModel(
            name='Test_Question',
        ),
    ]
